# Node Player Workflow.

name: NodePlayer

on: 
  workflow_dispatch:
  push:
    paths:
    - Source/Services/RPSLS.NodePlayer.Api/**
    - .github/workflows/node_player_cicd.yml    
    - Deploy/helm/node-player/**
    branches:
      - main    

jobs:
  buildpush:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./Source/Services/RPSLS.NodePlayer.Api
        file: ./Source/Services/RPSLS.NodePlayer.Api/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/node.player:gh-${{ github.sha }}
    - name: Helm registry login (GHCR)
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin
    - name: Package Helm chart
      run: |
        helm package Deploy/helm/node-player -d Deploy/helm/__charts --version 1.0.0-${{ github.sha }}
    - name: Push Helm chart to GHCR (OCI)
      run: |
        helm push Deploy/helm/__charts/node-player-1.0.0-${{ github.sha }}.tgz oci://ghcr.io/${{ github.repository_owner }}/charts
    - name: Generate config file
      shell: pwsh
      run: |
        az extension add --name application-insights
        Deploy/powershell/Generate-Config.ps1 -gvaluesTemplate gvalues.template.gh -resourceGroup ${{ secrets.RESOURCE_GROUP }} -outputFile _values-gh.yaml -aksHost ${{ secrets.AKS_HOST }} -resourceGroupAcr ${{ secrets.RESOURCE_GROUP_ACR }}
    - name: Install Helm Chart
      run: |
        helm upgrade --install -f Deploy/powershell/_values-gh.yaml --set image.repository=ghcr.io/${{ github.repository_owner }}/node.player --set image.tag=gh-${{ github.sha }} --set replicaCount=2 node-player oci://ghcr.io/${{ github.repository_owner }}/charts/node-player --version=1.0.0-${{ github.sha }}





